services:
  # services name
  db:
    image: mysql:8.4
    container_name: mysql_db
    # port tidak ada, db hanya diizinkan berkomunikasi dengan services di dalam container 
    env_file:
      - .env
    # tempat menyimpan data di path host atau bind mount. untuk data persisten, jika container dihapus data tidak hilang.
    # di host : di container. 
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE : ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
    # docker networks, untuk network antar container
    networks:
      - app-network

  app:
    # Build image yang ada di dockerfile
    build: .
    container_name: jastip_app
    env_file:
      - .env
    # working dir
    working_dir: /var/www/html
    # expose 'public' agar dapat diakses oleh webserver
    volumes:
      - app_public:/var/www/html/public
      - app_storage:/var/www/html/storage/app/public
    # menunggu db up
    depends_on:
      - db
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx_web_server
    ports:
      - "80:80"
    volumes:
      - app_public:/var/www/html/public:ro
      # langsung mengakses /public/storage agar tidak perlu php artisan storage:link
      - app_storage:/var/www/html/public/storage:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mysql_data:
  app_public:
  app_storage:

networks:
  app-network:
    driver: bridge